---
# The git repository to use for retrieving dotfiles. 
# Dotfiles should generally be laid out within the root directory of the repository.
dotfiles_repo: "https://github.com/ephimoff/dotfiles-min.git" 

# Add the hostkey for the repo url if not already added. 
# If ssh_opts contains "-o StrictHostKeyChecking=no", this parameter is ignored.
dotfiles_repo_accept_hostkey: no

# The local path where the dotfiles_repo will be cloned.
dotfiles_repo_local_destination: "~/Projects/dotfiles"

# The home directory where dotfiles will be linked. 
# Generally, the default should work, but in some circumstances, or when running the role 
# as sudo on behalf of another user, you may want to specify the full path.
dotfiles_home: "~"

# Which files from the dotfiles repository should be linked to the dotfiles_home
dotfiles_files:
  - .aliases
  - .functions
  - .gemrc
  - .gitconfig
  - .gitconfig.local
  - .gitignore_global
  - .gitmessage
  - .hushlogin
  - .inputrc
  - .mdlrc
  - .mdlrc.style.rb
  - .path
  - .textlintrc
  - .vimrc
  - .zshrc