---
# general vars
general:
  local_home: "{{ lookup('env','HOME') }}"

downloads: "{{general.local_home}}/.ansible-downloads/"

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes
