---
- name: Provision a mac
  hosts: local
  gather_facts: false
  vars_files:
    - default.config.yml
  roles:
    - {role: directories, tags: all}
    - {role: brew, tags: brew}
    - {role: ruby, tags: [dev, ruby]}
    - {role: yarn, tags: [dev, js]}
    - {role: mas, tags: all}
    - {role: zsh, tags: all}
    - {role: dotfiles, tags: dot}
    - {role: applications-preferences, tags: all}
    - {role: macos, tags: all}
    - {role: vim, tags: dev}
    - {role: ssh, tags: all}