---
- name: set up a mac
  hosts: localhost
  connection: local

  roles:
    - dirs 
    # - dotfiles
    # - templates
    # - macos
    # - brew
    # - cask
    # - mas
    # - additional_apps
    # - preferences
    # - oh_my_zsh