---
- name: set up a mac
  hosts: local
  gather_facts: false
  vars_files:
    - default.config.yml
  roles:
    - directories
    - brew
    - ruby
    - yarn
    - mas
    - zsh
    - dotfiles
    - applications-preferences
    - macos
    - vim
    - ssh