---
- name: Ensure Node and Yarn are installed
  homebrew: 
    name: "{{ item }}"
    state: present
  with_items:
    - node
    - yarn

- name: Ensure node packages are installed
  npm: 
    name: "{{ item }}"
    global: yes
  with_items: "{{ node_installed_packages }}"