---
- name: Ensure dotfiles repository is cloned locally
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
    accept_hostkey: "{{ dotfiles_repo_accept_hostkey }}"

- name: Backup existing dotfiles
  copy:
    src: "{{ general.local_home }}/{{ item }}"
    dest: "{{ dotfiles_backup_location }}"
  with_items: "{{ dotfiles_files }}"
  ignore_errors: yes

- name: Link dotfiles into home folder
  file:
    src: "{{ dotfiles_repo_local_destination }}/dotfiles/{{ item }}"
    dest: "{{ general.local_home }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ dotfiles_files }}"

- name: Link Scripts folder to home folder
  file:
    src: "{{general.local_home}}/Projects/scripts"
    dest: "{{ general.local_home }}/.scripts"
    state: link
    force: yes



