---
# A list of ssh_config sections defined as dictionaries. Entries must
# contain a `host` field and any set of ssh_config options.
#
# e.g.
# - host: "*"
#   HashKnownHosts: yes
#   GSSAPIAuthentication: yes
#   GSSAPIDelegateCredentials: no
# - host: example.com
#   ServerAliveInterval: 300
#   ServerAliveCountMax: 2

ssh_config_host_configs:
  - host: "*"
    TCPKeepAlive: yes
    ServerAliveInterval: 60
    ControlMaster: auto
    ControlPath: ~/.ssh/%C
    ControlPersist: 30
    ConnectTimeout: 5
  - host: github.com
    HostName: ssh.github.com
    Port: 443
    PasswordAuthentication: no
    IdentitiesOnly: yes
    IdentityFile: ~/.ssh/id_rsa
  - host: gitlab.com
    HostName: altssh.gitlab.com
    Port: 443
    User: git
    PasswordAuthentication: no
    IdentitiesOnly: yes
    IdentityFile: ~/.ssh/id_rsa
  - host: "192.168.*.* *.local localhost"
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
    LogLevel: ERROR

ssh_base_dir: "{{general.local_home}}/.ssh"
ssh_config_path: "{{ssh_base_dir}}/config"