---
# - name: apps | Ensure that Karabiner directory exists
#   file:
#     path: "{{general.local_home}}/.config/karabiner"
#     state: directory
#     mode: 0755
#   ignore_errors: yes

- name: apps | Symlink Karabiner-Elements prefs
  file:
    src: "{{general.local_home}}/Projects/ansible-dotfiles/files/karabiner/karabiner"
    dest: "{{general.local_home}}/.config/karabiner"
    state: link
    force: yes

- name: apps | Ensure that Spectacle directory exists
  file:
    path: "{{general.local_home}}/Library/Application\ Support/Spectacle"
    state: directory
    mode: 0755

- name: apps | Symlink Spectacle prefs
  file:
    src: "{{general.local_home}}/Projects/ansible-dotfiles/files/spectacle/Shortcuts.json"
    dest: "{{general.local_home}}/Library/Application\ Support/Spectacle/Shortcuts.json"
    state: link
    force: yes

- name: apps | Ensure that VS Code directory exists
  file:
    path: "{{general.local_home}}/Library/Application\ Support/Code/User"
    state: directory
    mode: 0755

- name: apps | Install VS Code extensions
  shell: "code --install-extension {{ item }}"
  with_items: "{{ vs_code_extensions }}"


- name: apps | Symlink VS Code prefs
  file:
    src: "{{general.local_home}}/Projects/ansible-dotfiles/files/vscode/{{ item }}"
    dest: "{{general.local_home}}/Library/Application\ Support/Code/User/{{ item }}"
    state: link
    force: yes
  with_items: "{{ vs_code_prefs }}"

- name: apps | open terminal theme of choice
  shell: "open {{ terminal_theme_location }}"
