---
- name: mas | Ensure MAS is installed.
  homebrew: 
    name: mas 
    state: present

- name: mas | Get MAS account status
  shell: mas account
  register: mas_account_result
  failed_when: mas_account_result.rc > 1
  changed_when: false


- name: mas | Sign in to MAS when email and password are provided
  shell: mas signin "{{ mas_email }}" "{{ mas_password }}"
  register: mas_signin_result
  when: mas_account_result.rc == 1 and mas_email != '' and mas_password != '' and not mas_signin_dialog

- name: mas | Sign in to MAS when email is provided, and complete password and 2FA using dialog.
  shell: mas signin "{{ mas_email }}" "{{ mas_password }}" --dialog
  register: mas_signin_result
  when: mas_signin_dialog and mas_account_result.rc == 1 and mas_email != ''

- name: mas | Ensure configured MAS apps are installed
  command: mas install "{{ item.id  }}"
  with_items: "{{ mas_installed_apps }}"
  ignore_errors: yes

- name: mas | Upgrade all apps (if configured)
  command: mas upgrade
  when: mas_upgrade_all_apps
  ignore_errors: yes