---
- name: Ensure Homebrew directory exists
  file:
    path: "{{ homebrew_install_path }}"
    state: directory
    mode: 0775
  become: yes

- name: Ensure homebrew is updated 
  homebrew:
    state: latest
    update_homebrew: yes

- name: Ensure configured taps are tapped
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Install configured cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_apps }}"
  ignore_errors: "{{ skip_errors }}"
  register: repeat_cask_install

- name: Try to install failed cask applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_apps }}"
  ignore_errors: "{{ skip_errors }}"
  when: "'Failed' in repeat_cask_install.stderr"

- name: Ensure configured homebrew packages are installed
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_installed_packages }}"
  ignore_errors: "{{ skip_errors }}"

- name: Upgrade all homebrew packages (if configured)
  homebrew:
    update_homebrew: yes 
    upgrade_all: yes
  when: homebrew_upgrade_all_packages

- name: Cleanup brew packages
  command: brew cleanup
