- name: Create useful directories if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items: "{{ folders }}"
    

- name: application installs
  include: homebrew.yml

- name: install brew apps
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ brew_apps }}"

- name: install cask apps
  homebrew_cask:
    name: "{{ item }}"
    state: installed
  with_items: "{{ cask_apps }}"

- name: cleanup brew packages
  command: brew cleanup

- name: setting up zsh with oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{general.local_home}}/.oh-my-zsh"

- name: install zsh
  include: zsh.yml

- name: install versions of ruby with rbenv
  include: ruby.yml

- name: apply application preferences
  include: apps.yml

- name: install vim plugins
  include: vim.yml

- name: symlink dotfiles
  include: dotfiles.yml

- name: apply system preferences
  include: system.yml

- name: install MAS apps
  include: mas.yml