---
- name: init rbenv
  shell: eval "$(rbenv init -)"

- name: install ruby versions
  shell: rbenv install {{ item }}
  with_items:
    - 2.0.0-p598
    - 2.2.0

- name: make 2.2 a global version
  shell: rbenv global 2.2.0

- name: install gems
  gem:
    name: {{ item }}
    state: present
  with_items:
    - bundler
    - mdl
    - rubocop
    - yaml-lint

- name: rehash rbenv
  shell: rbenv rehash
