---
- name: init rbenv
  shell: eval "$(rbenv init -)"

- name: check installed ruby versions
  shell: rbenv versions --bare
  register: rbenv_installed_ruby_versions
  changed_when: False

- name: install ruby versions
  command: "rbenv install {{ item }}"
  # when: rbenv_installed_ruby_versions.stdout.find("{{ item }}") == -1
  when: rbenv_installed_ruby_versions.stdout.find(item) == -1
  with_items: 
    - 2.0.0-p598
    - 2.2.0

- name: check default ruby version
  shell: rbenv global
  register: rbenv_installed_default_ruby_version
  changed_when: False

- name: set default ruby version
  vars: 
    rbenv_default_ruby_version: 2.2.0
  command: "rbenv global {{ rbenv_default_ruby_version }}"
  # when: rbenv_installed_default_ruby_version.stdout.find("{{ rbenv_default_ruby_version }}") == -1
  when: rbenv_installed_default_ruby_version.stdout.find(rbenv_default_ruby_version) == -1

# - name: install ruby versions
#   shell: "rbenv install {{ item }}"
#   with_items:
#     - 2.0.0-p598
#     - 2.2.0

# - name: make 2.2 a global version
#   shell: rbenv global 2.2.0

- name: install gems
  gem:
    name: "{{ item }}"
    state: present
  with_items:
    - bundler
    - mdl
    - rubocop
    - yaml-lint

- name: rehash rbenv
  shell: rbenv rehash
