---
- name: init rbenv
  shell: eval "$(rbenv init -)"

- name: check installed ruby versions
  shell: rbenv versions --bare
  register: rbenv_installed_ruby_versions
  changed_when: False

- name: install ruby versions
  command: "rbenv install {{ item }}"
  when: rbenv_installed_ruby_versions.stdout.find(item) == -1
  with_items: "{{ ruby_versions }}"

- name: check default ruby version
  shell: rbenv global
  register: rbenv_installed_default_ruby_version
  changed_when: False

- name: set default ruby version
  command: "rbenv global {{ default_ruby_version }}"
  when: rbenv_installed_default_ruby_version.stdout.find(default_ruby_version) == -1

- name: install gems
  gem:
    name: "{{ item }}"
    state: present
  with_items: "{{ ruby_gems }}"

- name: rehash rbenv
  shell: rbenv rehash
