- name: 'Finder: keep folders on top when sorting by name'
  shell: defaults write com.apple.finder _FXSortFoldersFirst -bool true

- name: 'Finder: show full path in title'
  shell: defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

- name: 'Finder: show status bar'
  shell: defaults write com.apple.finder ShowStatusBar -bool true

- name: 'Finder: show path bar'
  shell: defaults write com.apple.finder ShowPathbar -bool true

- name: 'Finder: when performing a search, search the current folder by default'
  shell: defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

- name: 'Finder: use column view in all Finder windows by default'
  shell: defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

- name: 'Finder: show all filename extensions'
  shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: 'Avoid creating .DS_Store files on network volumes'
  shell: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

- name: 'Avoid creating .DS_Store files on USB Volumes'
  shell: defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

- name: 'Expand save panel by default'
  shell: defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true

- name: 'Sets default save target to be a local disk, not iCloud'
  shell: defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

- name: 'Disable the `Are you sure you want to open this application?` dialog'
  shell: defaults write com.apple.LaunchServices LSQuarantine -bool false

- name: 'Show battery percent'
  shell: defaults write com.apple.menuextra.battery ShowPercent -bool true

- name: 'Trackpad: enable tap to click'
  shell: defaults -currentHost write NSGlobalDomain "com.apple.mouse.tapBehavior" -int 1

- name: 'Trackpad: disable look up'
  shell: defaults -currentHost write NSGlobalDomain "com.apple.trackpad.threeFingerTapGesture" -int 0

- name: 'Trackpad: enable 3 finger drag'
  shell: defaults -currentHost write NSGlobalDomain "com.apple.trackpad.threeFingerDragGesture" -int 1

- name: 'Trackpad: disable swipe between pages'
  shell: defaults write NSGlobalDomain AppleEnableSwipeNavigateWithScrolls -bool false

- name: 'Keyboard: enable full keyboard access for all controls, (e.g. enable Tab in modal dialogs)'
  shell: defaults write NSGlobalDomain AppleKeyboardUIMode -int 2

- name: 'Keyboard: Disable auto-correct'
  shell: defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

- name: 'Mail.app: copy email addresses as \`foo@example.com\` instead of \`Foo Bar <foo@example.com>\`'
  shell: defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

- name: 'Safari: prevent Safari from opening ‘safe’ files automatically after downloading'
  shell: defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

- name: 'Safari: Disable Safari’s thumbnail cache for History and Top Sites'
  shell: defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

- name: 'Safari: Enable Safari’s debug menu'
  shell: defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

- name: 'Safari: Stop Safari sending searches to Apple'
  shell: defaults write com.apple.Safari UniversalSearchEnabled -bool false


