# ruby versions to install
ruby_versions:
  - 2.0.0-p598
  - 2.2.0
  - 2.5.1

# ruby default version
default_ruby_version: 2.5.1

# ruby gems to install
ruby_gems:
  - bundler
  - mdl
  - rubocop
  - yaml-lint