---
# mas settings
mas_email: ""
mas_password: ""
mas_installed_apps:
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 443987910, name: "1Password" }
  - { id: 775737590, name: "iA Writer" }
  - { id: 407963104, name: "Pixelmator" }
mas_upgrade_all_apps: no
mas_signin_dialog: no